### ISSUE TITLE
Animals stop to breed

### ISSUE THREAD

**Issue by inexcode** [inexcode/HumanlikeLifeStages#12]
[Marquis](https://steamcommunity.com/id/MarquisAesir) reported on steam:
>I found out that this mod destroys animal fertility if installed with wooher, birds and bees, school and children. it stops animals from breeding setting their fertility to none

Need confirmations and more details.
My config only have school and children from that list, and animal fertility works. 

UPD:
>Animals not breeding, I think this mod sets animals private parts to none exsistant this is why they don't reproduce setting their fertility to none. Mod Order:
1. Core
2. Hugslib
3. Birds and the bees
4. children, school and learning 
5. Woohooer
6. Humanlike Life Stages - Age Matters 2

**Comment by UnscathedAnimal** [comment]
I also had this problem, but just got it fixed. Your answer is right inside the Woohooer description:

"If your animals loose fertility
Try loading mods this way:
1. Humanlike Life Stages
2. Birds and the bees
3. Woohooer"

This should probably be added to the HLLS description too.
