### ISSUE TITLE
Both genders have both parts?

### ISSUE THREAD

**Issue by DeafPotatto** [inexcode/HumanlikeLifeStages#15]
For some reason with all races, I have tried this with they end up having both wombs/ovaries _AND_ testes. Is there anything I am doing wrong?

Quick note: I believe my setting are correct. Please correct me if im wrong!
![screenshot 28](https://user-images.githubusercontent.com/38776307/49558795-95320b80-f8c9-11e8-8b87-05e35447e9ae.png)

**Comment by inexcode** [comment]
Did this happen to **all** your pawns? There's an intersex setting, which configures the chance of this to happen.

**Comment by DeafPotatto** [comment]
Oh...
![screenshot 30](https://user-images.githubusercontent.com/38776307/49560540-1a202380-f8d0-11e8-8d4c-8c3b2798517d.png)
I may be an idiot...

**Comment by inexcode** [comment]
Was it like this by default, or did you do it yourself?
