### ISSUE TITLE
Full rewrite needed?

### ISSUE THREAD

**Issue by inexcode** [inexcode/HumanlikeLifeStages#2]
Actually, that's not so clear about licensing stuff of specifically this mod.
Right now there are no changes in code itself, so we didn't create a derivative yet.

**Comment by WinstontheButterfly** [comment]
So the thing is that she didn't changing anything at all in the mod at all, its exactly the same just with the Licence file updated. Another thing is that there really is no laws governing copyright over video game mods. 

But if we can get permission from Ludeon studios we can work save the mod and begin supporting it ourselves its part of their EULA agreement!

**Comment by WinstontheButterfly** [comment]
I have sent them both and Email and contacted them on facebook

**Comment by inexcode** [comment]
Thanks, keep me updated!

**Comment by EPSIL0N** [comment]
Posting to say I'm also waiting on the response as I have some of the mods she either never backed up or has deleted the repositories and have no clear information on if they had any licensing limitations.

**Comment by LenKagetsu** [comment]
Use wayback machine or google cache to see if there are licenses for them. If she declared any of them as public domain at any point you're good. There's no backsies on that or on CC licenses.

**Comment by inexcode** [comment]
Whoah!
Could you please quote the answer so we can be sure?

**Comment by WinstontheButterfly** [comment]
[https://imgur.com/xUzjB2P](the email)

**Comment by inexcode** [comment]
Yay!
Thank you a lot for helping with that!
Now nothing will stop us from updating these mods.

**Comment by EPSIL0N** [comment]
Of the ones not on github I've got embassy, tv and insecticide, do we happen to know if anything other than older versions of mods is missing from the collection?

**Comment by WinstontheButterfly** [comment]
No problem! 

and she used to have a town Guard mod, that let you assign guards on rotations and the like

**Comment by EPSIL0N** [comment]
A version of guardduty was on her github, I am hoping she didn't deliberately ruin the copies there before people could get them altho it seems her sabotage may only have been skin deep for most mods.

**Comment by WinstontheButterfly** [comment]
i think at most it was skin deep, still cant be too sure

**Comment by inexcode** [comment]
I've forked safe version of guard duty, btw: https://github.com/inexcode/GuardDuty

**Comment by inexcode** [comment]
To be 100% sure we should rebuild binaries, but they haven't changed during the sabotage.

**Comment by inexcode** [comment]
Also, found out that @Saint-of-Grey panic-forked a lot of her mods. That may be useful.

**Comment by Saint-of-Grey** [comment]
Oh hey a mention.

I have all of her rimworld related repositories forked. Animated TV and insecticide were empty repos, and I'm afraid embassy was only on steam. Geneseed was out of date, too, I've recompiled that against 1.0. No major changes from when she had her meltdown other than name and the license on six of the repos (The ones without rimworld in the name in my repositories), I'm pretty sure the new license only applies to any versions of her mod moving forward (which don't exist).

**Comment by EPSIL0N** [comment]
I think I'm ready to reup those three. In the about file what should I change other than adding [fixed] and changing author to community fork of  ?

**Comment by inexcode** [comment]
@EPSIL0N Probably it's a good idea to change url field to GitHub repository link.
Also, don't forget to delete old PublishedField.txt, so you can upload your fork on Steam.
When you do, hit me up with workshop links so I add them to my collection of resurrected mods.

**Comment by EPSIL0N** [comment]
I'll post here to let you know. Which github did you have in mind or did you want me to also upload a copy of the files to github as alice's hub is empty or non-existant for Tv, embassy and insecticide.

**Comment by inexcode** [comment]
Yeah, it would be great if you upload them on GitHub.

**Comment by EPSIL0N** [comment]
Should be up now, here are the links
https://steamcommunity.com/profiles/76561197983646208/myworkshopfiles/?appid=294100

https://github.com/EPSIL0N/Embassy
https://github.com/EPSIL0N/Insecticide
https://github.com/EPSIL0N/TVRimworld

**Comment by inexcode** [comment]
Great, thanks!
Added to collection.
