### ISSUE TITLE
Option to disable secondary characteristics

### ISSUE THREAD

**Issue by inexcode** [inexcode/HumanlikeLifeStages#5]
As [Mirith](https://steamcommunity.com/profiles/76561198072986862) said on Steam:
> Also, I have a tiny question. Do you think it would be possible to add an option to disable breast added by this mod? I'm using another one that does it already and I must say, all those 4-breasted women do look rather hilarious.

I can see two solutions:
1. Auto-disable if another mod found
2. Manual configuration in mod settings.

**Comment by WinstontheButterfly** [comment]
i think the best option would be manual configuration in mod settings, also push support for the Prepare Carefully mod as well!

**Comment by HakariTenrai** [comment]
I second support for the EdB Prepair Carefully mod... While I can generally use the dev console to fix characters how I want them after the fact, I prefer to use prepair carefully to hand-tailor all of my characters before hand, and being able to use it with this mod would be a Plus Ultra experience!
